services:
  postgres:
    image: docker.io/postgres:14-alpine
    healthcheck:
      test: ["CMD", "/usr/local/bin/pg_isready"]
      start_period: 10s
    environment:
      POSTGRES_USER: stustapay
      POSTGRES_DB: stustapay
      POSTGRES_PASSWORD: stustapay
    ports:
    - 5433:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
