name: chip_debug app
on:
  workflow_call:
  pull_request:
    paths:
    - "app/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: get java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: build with gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assemble
          build-root-directory: chip_debug/
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: chip_debug debug build
          # release variant: ./app/app/build/outputs/apk/release/app-release-unsigned.apk
          path: ./app/chip_debug/build/outputs/apk/debug/app-debug.apk

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: get java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: test with gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
          build-root-directory: chip_debug/

      - name: lint with gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: lint
          build-root-directory: chip_debug/

      - name: Upload lint report
        uses: actions/upload-artifact@v3
        with:
          name: chip_debug lint-report
          path: ./app/chip_debug/build/reports/lint-results-debug.html
